import type { Dish } from '@/types';

// Temporary mock data. Will be replaced by a Supabase query.
export const mockDishes: Dish[] = [
  {
    id: 'dish-1',
    name: 'Burrata & heirloom tomato',
    description: 'Creamy burrata, heirloom tomatoes, basil oil, sourdough crisp',
    price: 16,
    category: 'Starters',
    tags: ['Vegetarian'],
    isAvailable: true,
  },
  {
    id: 'dish-2',
    name: 'Charred octopus',
    description: 'Smoked paprika, crushed potatoes, salsa verde',
    price: 24,
    category: 'Starters',
    tags: ['Gluten-Free'],
    isAvailable: true,
  },
  {
    id: 'dish-3',
    name: 'Truffle fries',
    description: 'Hand-cut fries, truffle oil, aged parmesan',
    price: 9,
    category: 'Starters',
    tags: ['Vegetarian'],
    isAvailable: true,
  },
  {
    id: 'dish-4',
    name: 'Braised short rib',
    description: 'Red wine jus, celeriac purée, glazed carrots',
    price: 28,
    category: 'Mains',
    tags: ['Gluten-Free'],
    isAvailable: true,
  },
  {
    id: 'dish-5',
    name: 'Wild mushroom risotto',
    description: 'Porcini, thyme, parmesan, brown butter',
    price: 22,
    category: 'Mains',
    tags: ['Vegetarian', 'Gluten-Free'],
    isAvailable: true,
  },
  {
    id: 'dish-6',
    name: 'Seasonal greens',
    description: 'Charred broccolini, chilli, garlic, toasted almonds',
    price: 12,
    category: 'Mains',
    tags: ['Vegetarian', 'Spicy'],
    isAvailable: true,
  },
  {
    id: 'dish-7',
    name: 'Basque cheesecake',
    description: 'Burnt top, soft centre, seasonal berries',
    price: 9,
    category: 'Desserts',
    tags: ['Vegetarian'],
    isAvailable: true,
  },
  {
    id: 'dish-8',
    name: 'Chocolate fondant',
    description: 'Warm centre, vanilla bean ice cream',
    price: 10,
    category: 'Desserts',
    tags: ['Vegetarian'],
    isAvailable: false,
  },
  {
    id: 'dish-9',
    name: 'Homemade lemonade',
    description: 'Lemon, mint, cane sugar',
    price: 5,
    category: 'Drinks',
    tags: ['Vegetarian', 'Gluten-Free'],
    isAvailable: true,
  },
  {
    id: 'dish-10',
    name: 'Glass of Albariño',
    description: 'Rías Baixas, Spain, 150 ml',
    price: 11,
    category: 'Drinks',
    tags: ['Gluten-Free'],
    isAvailable: true,
  },
];
